package com.lzy.pojo;

public class ProductImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.img_name
     *
     * @mbg.generated
     */
    private String imgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.id
     *
     * @return the value of productimg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.id
     *
     * @param id the value for productimg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.img_name
     *
     * @return the value of productimg.img_name
     *
     * @mbg.generated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.img_name
     *
     * @param imgName the value for productimg.img_name
     *
     * @mbg.generated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }
}